# Generated by Django 3.2.23 on 2023-11-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(default='0', max_length=254),
        ),
    ]
